eureka:
  client:
    service-url:
      register-with-eureka: true
      defaultZone: http://gateway.naresh.com/eureka/
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

